<b>RESPONSE EP 1:</b><BR>https://www.youtube.com/watch?v=0pDE4VX_9Kk<br>
John Berger, the host of <i>Ways of Seeing</I> begins a discussion about traditional European paintings and how the invention of the camera has changed the way the world interacts and understands paintings. While some paintings acquire their meaning though its location, such as chapel paintings, others rely on the painting itself. Those paintings that are not location specific, are now more manipulable after the invention of the camera. The camera can take a small section of a whole painting and call it a painting in itself and therefore give that section its own meaning. The camera can also change the meaning and emotion of a painting by adding sound. I think that sound might be the strongest way to change the emotional response a viewer has to a painting. With music a single painting can be made to feel romantic, or horrifying. For example, I grew up with two older brothers: 6 and 3 years older than I. I was allowed to watch movies that were not necessarily age appropriate for me. When we would watch scary movies I remember my brothers telling me to close my eyes, however, I would still be quite scared, because the music added to much of that emotion. Afterwards, we decided that instead we would mute the T.V. Surprisingly doing so diminished my fear far more than closing my eyes ever did. That’s the power of the camera. <br><br>
<b>RESPONSE EP 2:</b><br>https://www.youtube.com/watch?v=m1GI8mNU5Sg<br>
This episode goes over the incredible depiction of nude women displayed on so many traditional European paintings. As a woman I can agree with the episode when it says that most women are always aware of eyes on them, even their own eyes. I agree that when I go out to meet girlfriends I find myself asking the group whether or not we are dressing up. I haven't thought too hard about this but I believe this is because I wouldn't want to be the one that is less approachable, even though most of the time we choose not to dress up. Paintings that involve nudity almost always include a nude woman. The woman is almost always lying looking away with a blank stare; portraying submission towards a male spectator. Perhaps during the time that this video was released, in 1972,  women were much more submissive toward men; however, since then, feminism and women empowerment has increased dramatically. Women today are scientists, doctors, soldiers, and no longer do we feel as much submission from the male gender. <br><br>
 
<b>RESPONSE EP 3:</b><br>https://www.youtube.com/watch?v=Z7wi8jd7aC4&t=1348s<br>
Like most, I have always thought of traditional European paintings as the elite of all genres of paintings. Perhaps this is because so many of those paintings promote luxury and wealth. This episode went into some depth about what certain objects and animals were meant to represent in paintings. He mentioned that some objects such as fruits, houses, and even pedigree animals were a way to display your wealth in a painting. Portraits were made especially to promote wealth and power. Today many people promote their “wealth” on social media, however because it is available to the average person, many of those “luxury objects” have become devalued. Everyone can post portraits on Instagram, it doesn't promote luxury anymore. Fruits have been replaced by fancy dinners, which get posted A LOT online. People who are wealthy display their wealth by posting pictures of outfits, or of themselves on vacation, and so on. <br><br>
 
<b>RESPONSE EP 4:</b><br> https://www.youtube.com/watch?v=5jTUebm73IY<br>
Publicity ads even today offer ways in which consumers can exchange their money for glamour. Publicity plays upon the fear of being undesirable. Berger explains that this tradition has been passed on from traditional oil paintings. Traditional oil painters painted a part of life in which they had already achieved, however publicity ads offer photographs of a life we are yet to accomplish, a life which we desire. One strategy used by commercial photographs is posing their models in similar poses as those wealthy people in oil paintings. Another strategy is by placing an oil paintings in the part of the background of a publicity ad. Take the well known Dos X commercials with the most interesting man in the world. He is often sitting down on fine leather furniture in a dark room, a similar setting as an oil painting portrait. To top it off, he is often surrounded by one or two women. This entire scene suggest the man is wealthy and desirable. So if you drink Dos X, you are more likely to be successful with money and the ladies. This is obviously not the case, but does it make you want to give it a shot anyway, yes. 
